name: Devops_workspace

on:
  workflow_dispatch:
  #push:
    #branches:
     # - main
  #pull_request:
   # branches:
     # - main
env:
  IMAGE_TAG: latest
jobs:
  build:
    runs-on: [ aws-linux ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
           python-version: '3.10'
       
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Run tests
      #   run: python3 
     
      # - name: Run Python script
      #   run: |
      #     python src/app.py 

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker Image
        run: |
         docker build -t ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG .

      - name: Push Docker Image to ECR
        run: |
          docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG
          
      # - name: SonarQube Scan
      #   uses: sonarsource/sonarqube-scan-action@v2
      #   env:
      #      SONAR_TOKEN: ${{ secrets.sonar_creds }}
      #      SONAR_HOST_URL: https://sonarcloud.io
      #      SONAR_SCANNER_OPTS: "-Xmx1024m"
       
            

      # - name: Upload HTML as artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: html-table-output
      #     path: output/index.html
