name: Devops_workspace

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: [ azure-workspace-ubuntu ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
       
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest
      - name: Run Flask App 
        run: |
             python app.py &
             sleep 5
      - name: checking the app 
        run: |
          curl -s http://127.0.0.1:5000 || echo "Flask app failed to start!"
           
