name: Devops_workspace

on:
  workflow_dispatch:
  #push:
    #branches:
     # - main
  #pull_request:
   # branches:
     # - main

jobs:
  build:
    runs-on: [ aws-linux ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
           python-version: '3.10'
       
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python3 
     
      - name: Run Python script
        run: |
          python /src/app.py

      - name: Upload HTML as artifact
        uses: actions/upload-artifact@v4
        with:
          name: html-table-output
          path: output/index.html
